name    'puppet-drac'
version '0.0.5'
author 'newrelic'
license 'Apache License, Version 2.0'
summary 'Puppet management of drac settings via racadm'
description 'Enforce drac card settings in puppet.'
project_page 'http://github.com/newrelic/puppet-drac'
